### ISSUE TITLE
DNS not working when starting with DHCP

### ISSUE THREAD

**Issue by paulanthonywilson** [nerves-project/nerves_io_ethernet#2]
Workaround I am using is

```
    File.write("/etc/resolv.conf", "nameserver 8.8.8.8\n")
```

in the application start, before `Nerves.IO.Ethernet.start eth0`.

**Comment by ghitchens** [comment]
Resolved in https://github.com/nerves-project/nerves_io_ethernet/commit/785310644c16182d7993b641af539d6a0a2d9865

**Comment by paulanthonywilson** [comment]
Works great for me, thanks. :+1:
